package com;
import java.awt.desktop.ScreenSleepEvent;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.Map;

public class Text {
    String text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mollis nunc sed id semper. Erat imperdiet sed euismod nisi porta lorem mollis aliquam ut. Elementum nibh tellus molestie nunc non blandit massa enim nec. Enim ut sem viverra aliquet eget sit. Nibh tellus molestie nunc non blandit massa. Eu consequat ac felis donec et odio pellentesque. Arcu non odio euismod lacinia at quis risus sed vulputate. Tellus elementum sagittis vitae et leo duis. Elit sed vulputate mi sit amet. Et ultrices neque ornare aenean euismod. Id faucibus nisl tincidunt eget nullam non. Posuere lorem ipsum dolor sit amet consectetur adipiscing elit duis. Facilisis magna etiam tempor orci eu. Tellus pellentesque eu tincidunt tortor. A condimentum vitae sapien pellentesque. Netus et malesuada fames ac turpis. Eget est lorem ipsum dolor." +
            "Suspendisse in est ante in nibh mauris cursus mattis. Dui faucibus in ornare quam viverra orci sagittis eu volutpat. Eget sit amet tellus cras adipiscing enim eu. Orci sagittis eu volutpat odio facilisis mauris sit amet massa. Lorem dolor sed viverra ipsum nunc aliquet bibendum. Pulvinar proin gravida hendrerit lectus a. Orci nulla pellentesque dignissim enim sit amet venenatis. Tristique risus nec feugiat in fermentum posuere urna nec. Malesuada nunc vel risus commodo viverra. At lectus urna duis convallis. Praesent tristique magna sit amet purus. Purus ut faucibus pulvinar elementum integer. Nulla porttitor massa id neque aliquam vestibulum morbi. Erat pellentesque adipiscing commodo elit at imperdiet. Adipiscing tristique risus nec feugiat. In fermentum et sollicitudin ac orci phasellus egestas tellus. Dui ut ornare lectus sit amet est placerat in egestas. Eget magna fermentum iaculis eu non. Ac tincidunt vitae semper quis lectus nulla at volutpat. Non sodales neque sodales ut." +
            "Netus et malesuada fames ac turpis egestas. Varius vel pharetra vel turpis nunc eget lorem dolor. Nulla aliquet enim tortor at auctor urna nunc id. Pellentesque habitant morbi tristique senectus et netus et malesuada fames. Facilisis volutpat est velit egestas dui. Sapien faucibus et molestie ac. Feugiat nibh sed pulvinar proin. Sit amet risus nullam eget. Amet tellus cras adipiscing enim eu turpis. Vulputate ut pharetra sit amet aliquam id diam maecenas. Tristique nulla aliquet enim tortor at auctor urna nunc id. Auctor elit sed vulputate mi sit amet mauris commodo. Hendrerit dolor magna eget est. Felis eget nunc lobortis mattis aliquam faucibus purus. Ac tortor vitae purus faucibus ornare suspendisse sed nisi." +
            "Cursus in hac habitasse platea dictumst quisque sagittis. Quis viverra nibh cras pulvinar mattis nunc sed blandit libero. Diam ut venenatis tellus in metus vulputate eu scelerisque felis. Consectetur lorem donec massa sapien faucibus et molestie ac. Felis bibendum ut tristique et egestas quis ipsum suspendisse. Sed pulvinar proin gravida hendrerit lectus. Vitae tortor condimentum lacinia quis. Fusce id velit ut tortor pretium. Amet luctus venenatis lectus magna fringilla. Pretium fusce id velit ut tortor pretium viverra suspendisse potenti. Accumsan sit amet nulla facilisi morbi tempus iaculis urna id. Tincidunt augue interdum velit euismod in pellentesque massa placerat duis. Semper auctor neque vitae tempus quam pellentesque nec. At lectus urna duis convallis convallis tellus id interdum. Consequat ac felis donec et odio pellentesque. Nulla at volutpat diam ut venenatis tellus in. Et molestie ac feugiat sed." +
            "Lacinia at quis risus sed vulputate odio. Lectus mauris ultrices eros in cursus turpis massa. Elementum nisi quis eleifend quam. Non diam phasellus vestibulum lorem sed. Tincidunt vitae semper quis lectus nulla at. Vivamus arcu felis bibendum ut tristique et egestas quis. Odio facilisis mauris sit amet. Massa tincidunt dui ut ornare lectus sit amet est placerat. Quisque egestas diam in arcu cursus euismod quis viverra. Sit amet massa vitae tortor condimentum lacinia. Enim sit amet venenatis urna. Augue ut lectus arcu bibendum at." +
            "Non blandit massa enim nec dui nunc mattis. Pellentesque adipiscing commodo elit at. Nec dui nunc mattis enim ut tellus elementum. Enim nunc faucibus a pellentesque sit amet porttitor eget dolor. Sem fringilla ut morbi tincidunt augue. Enim sed faucibus turpis in eu mi bibendum neque egestas. Pulvinar elementum integer enim neque volutpat ac tincidunt vitae semper. Pretium lectus quam id leo in vitae turpis. Ante in nibh mauris cursus mattis molestie. Pharetra diam sit amet nisl suscipit adipiscing bibendum est ultricies. Pharetra massa massa ultricies mi quis hendrerit. A diam maecenas sed enim ut sem viverra aliquet. Scelerisque fermentum dui faucibus in ornare quam viverra orci. Molestie nunc non blandit massa. Massa massa ultricies mi quis hendrerit. Justo eget magna fermentum iaculis eu non diam. Consectetur a erat nam at lectus urna duis convallis. Sodales neque sodales ut etiam. Id aliquet lectus proin nibh nisl condimentum id venenatis. Odio ut enim blandit volutpat maecenas volutpat." +
            "Enim tortor at auctor urna. Turpis cursus in hac habitasse. At consectetur lorem donec massa sapien. Erat velit scelerisque in dictum non consectetur a. Dictum non consectetur a erat nam at lectus. Fames ac turpis egestas integer eget aliquet. Nulla pharetra diam sit amet nisl suscipit adipiscing bibendum est. Pretium viverra suspendisse potenti nullam ac tortor vitae purus. At volutpat diam ut venenatis tellus in metus. Nisl rhoncus mattis rhoncus urna." +
            "Nibh mauris cursus mattis molestie a iaculis at erat pellentesque. Diam donec adipiscing tristique risus. Quisque non tellus orci ac auctor. Massa vitae tortor condimentum lacinia quis vel eros donec. In ornare quam viverra orci sagittis. Lacinia quis vel eros donec. Pellentesque id nibh tortor id aliquet lectus proin nibh nisl. Diam maecenas ultricies mi eget mauris pharetra et ultrices neque. Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus et. Non nisi est sit amet facilisis." +
            "Ut sem viverra aliquet eget. Convallis tellus id interdum velit laoreet. Iaculis eu non diam phasellus. Tellus pellentesque eu tincidunt tortor aliquam. Lectus arcu bibendum at varius vel pharetra. Neque convallis a cras semper auctor neque vitae tempus quam. Aliquam nulla facilisi cras fermentum. Nunc sed id semper risus in hendrerit gravida rutrum. Molestie ac feugiat sed lectus vestibulum. In hendrerit gravida rutrum quisque non tellus orci ac auctor. Arcu felis bibendum ut tristique et egestas quis. At ultrices mi tempus imperdiet nulla malesuada. Tincidunt arcu non sodales neque sodales." +
            "Ultricies mi quis hendrerit dolor magna eget. Facilisis magna etiam tempor orci eu lobortis elementum nibh. Sit amet cursus sit amet. A erat nam at lectus urna duis convallis convallis. Ullamcorper eget nulla facilisi etiam dignissim diam quis enim. Neque convallis a cras semper. Fermentum leo vel orci porta. Malesuada pellentesque elit eget gravida cum sociis natoque. Ultricies integer quis auctor elit sed vulputate mi sit amet. Pellentesque dignissim enim sit amet venenatis. Faucibus in ornare quam viverra orci sagittis eu volutpat odio. Vulputate ut pharetra sit amet aliquam id diam. Urna neque viverra justo nec ultrices dui sapien eget mi.";



    public static void main(String[] args) {
        Text text = new Text();
        Manipulator manip = new Manipulator();
        System.out.println("Sentences: " + manip.Sentences(text.text));
        System.out.println("Words: " + manip.Words(text.text));
        System.out.println("Letters: " + manip.Letters(text.text));
        System.out.println("Vowels: " + manip.Vowels(text.text));
        System.out.println("Consonants: " + manip.Consonants(text.text));
        manip.OftenWords(text.text);
        System.out.println("Longest word: " + manip.LongestWord(text.text));
    }

}
